"""Self-service portal for interviewees.

Interviewees access this via a JWT token link (generated by a manager).
No user login required — the token identifies the interviewee.
"""

from datetime import UTC, datetime, timedelta
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from jose import JWTError, jwt
from pydantic import BaseModel

from grc_backend.api.deps import DBSession, ManagerUser, get_settings_dep
from grc_backend.config import Settings
from grc_backend.core.errors import NotFoundError
from grc_core.repositories import InterviewRepository

router = APIRouter()

PORTAL_TOKEN_EXPIRE_DAYS = 30


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class PortalTokenCreate(BaseModel):
    """Request to create a portal access token for an interviewee."""

    expires_days: int = PORTAL_TOKEN_EXPIRE_DAYS


class PortalTokenResponse(BaseModel):
    """Response with the generated portal link."""

    token: str
    expires_at: datetime
    interviewee_id: str
    portal_url: str


class PortalProfile(BaseModel):
    """Interviewee profile visible in the portal."""

    id: str
    name: str | None
    email: str | None
    department: str | None
    position: str | None


class PortalProfileUpdate(BaseModel):
    """Fields the interviewee can self-edit."""

    name: str | None = None
    department: str | None = None
    position: str | None = None


class PortalInterview(BaseModel):
    """Interview summary for the interviewee portal."""

    id: str
    task_name: str | None
    status: str
    scheduled_at: datetime | None
    language: str


class PortalDashboard(BaseModel):
    """Full portal dashboard response."""

    profile: PortalProfile
    interviews: list[PortalInterview]


# ---------------------------------------------------------------------------
# Manager endpoint — generate portal token
# ---------------------------------------------------------------------------


@router.post("/interviewees/{interviewee_id}/portal-token", response_model=PortalTokenResponse)
async def create_portal_token(
    interviewee_id: str,
    db: DBSession,
    current_user: ManagerUser,
    settings: Annotated[Settings, Depends(get_settings_dep)],
    body: PortalTokenCreate | None = None,
) -> PortalTokenResponse:
    """Generate a portal access token for an interviewee."""
    from grc_core.models.interviewee import Interviewee

    result = await db.get(Interviewee, interviewee_id)
    if not result:
        raise NotFoundError(
            message="Interviewee not found",
            resource_type="Interviewee",
            resource_id=interviewee_id,
        )

    expires_days = body.expires_days if body else PORTAL_TOKEN_EXPIRE_DAYS
    expires_at = datetime.now(UTC) + timedelta(days=expires_days)

    token = jwt.encode(
        {
            "sub": interviewee_id,
            "type": "portal",
            "exp": expires_at,
        },
        settings.secret_key,
        algorithm=settings.jwt_algorithm,
    )

    return PortalTokenResponse(
        token=token,
        expires_at=expires_at,
        interviewee_id=interviewee_id,
        portal_url=f"/portal/{token}",
    )


# ---------------------------------------------------------------------------
# Public endpoints — accessed with portal token
# ---------------------------------------------------------------------------

public_router = APIRouter()


def _decode_portal_token(token: str, settings: Settings) -> str:
    """Decode and validate a portal token, returning the interviewee_id."""
    try:
        payload = jwt.decode(token, settings.secret_key, algorithms=[settings.jwt_algorithm])
        if payload.get("type") != "portal":
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="無効なトークンタイプです",
            )
        return payload["sub"]
    except JWTError as err:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="ポータルリンクが無効または期限切れです",
        ) from err


@public_router.get("/{token}", response_model=PortalDashboard)
async def get_portal_dashboard(
    token: str,
    db: DBSession,
    settings: Annotated[Settings, Depends(get_settings_dep)],
) -> PortalDashboard:
    """Get the interviewee's portal dashboard (profile + interviews)."""
    from grc_core.models.interviewee import Interviewee

    interviewee_id = _decode_portal_token(token, settings)

    interviewee = await db.get(Interviewee, interviewee_id)
    if not interviewee:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="回答者が見つかりません")

    profile = PortalProfile(
        id=interviewee.id,
        name=interviewee.name,
        email=interviewee.email,
        department=interviewee.department,
        position=interviewee.position,
    )

    # Fetch interviews for this interviewee
    interview_repo = InterviewRepository(db)
    interviews_raw = await interview_repo.get_multi(
        filters={"interviewee_id": interviewee_id}, limit=50
    )

    interviews: list[PortalInterview] = []
    for iv in interviews_raw:
        task_name = None
        if iv.task:
            task_name = iv.task.name
        interviews.append(
            PortalInterview(
                id=iv.id,
                task_name=task_name,
                status=iv.status.value if hasattr(iv.status, "value") else str(iv.status),
                scheduled_at=iv.created_at,
                language=iv.language,
            )
        )

    return PortalDashboard(profile=profile, interviews=interviews)


@public_router.put("/{token}/profile", response_model=PortalProfile)
async def update_portal_profile(
    token: str,
    update_data: PortalProfileUpdate,
    db: DBSession,
    settings: Annotated[Settings, Depends(get_settings_dep)],
) -> PortalProfile:
    """Update the interviewee's own profile (name, department, position)."""
    from grc_core.models.interviewee import Interviewee

    interviewee_id = _decode_portal_token(token, settings)

    interviewee = await db.get(Interviewee, interviewee_id)
    if not interviewee:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="回答者が見つかりません")

    if update_data.name is not None:
        interviewee.name = update_data.name
    if update_data.department is not None:
        interviewee.department = update_data.department
    if update_data.position is not None:
        interviewee.position = update_data.position

    await db.commit()
    await db.refresh(interviewee)

    return PortalProfile(
        id=interviewee.id,
        name=interviewee.name,
        email=interviewee.email,
        department=interviewee.department,
        position=interviewee.position,
    )
